skip_branch_with_pr: true
image: Visual Studio 2017

install:
  - cinst gitversion.portable -y

platform: Any CPU
configuration: Release

before_build:
  - dotnet restore Source
  - gitversion /l console /output buildserver

build_script:
  - dotnet build Source\CodeGenerator -o bin
  - dotnet Source\CodeGenerator\bin\CodeGenerator.dll Source\QuantityTypes\units.csv Source\QuantityTypes\Quantities
  - dotnet build Source\QuantityTypes.Csv /p:Version=%GitVersion_NuGetVersionV2%

artifacts:
  - path: Output
    name: QuantityTypes-$(GitVersion_SemVer)
    type: zip
  - path: '**\*.nupkg'
    name: QuantityTypes-$(GitVersion_SemVer)
    type: zip
