skip_branch_with_pr: true
image: Visual Studio 2017

install:
  - cinst gitversion.portable -y


before_build:
  - dotnet restore Source\QuantityTypes.sln
  - gitversion /l console /output buildserver

build_script:
  - dotnet build Source\CodeGenerator -o bin
  - dotnet Source\CodeGenerator\bin\CodeGenerator.dll Source\QuantityTypes\units.csv Source\QuantityTypes\Quantities
  - dotnet build -c Release Source\QuantityTypes /p:Version=%GitVersion_NuGetVersionV2%
  - dotnet build -c Release Source\QuantityTypes.Csv /p:Version=%GitVersion_NuGetVersionV2%
  - dotnet build -c Release Source\QuantityTypes.Dynamic /p:Version=%GitVersion_NuGetVersionV2%

test_script:
  - dotnet test Source\QuantityTypes.Tests
  - dotnet test Source\QuantityTypes.Csv.Tests
  - dotnet test Source\QuantityTypes.Dynamic.Tests

artifacts:
  - path: '**\*.nupkg'
